version: "3"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin    
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod

volumes:
  mongodata: